import Link from "next/link";
import { getPage } from "@/lib/queries";
import ProjectCTA from "@/components/ProjectCTA";
import SectionHead from "@/components/SectionHead";
export const metadata = { title: "OEM / ODM Lighting Development", description: "Discuss lighting product development, custom functions, finishes, branding, packaging and sample approval with XINSHERN.", alternates: { canonical: "/oem-odm" } };
const options = [["Product & Function", "Discuss lighting effects, controls, power supply and the functions your customers need."], ["Design & Finish", "Explore product appearance, materials, colors and surface finishes."], ["Brand & Packaging", "Plan your logo, labels, user manual and retail packaging."], ["Quality & Market", "Define inspection criteria and the testing requirements for your target market."], ["Samples & Production", "Agree sample requirements, order quantities and production milestones."]];
export default async function OEM() {
  const page = await getPage("oem-odm");
  const saved = Array.isArray(page?.content?.sections) ? page.content.sections as {title?:string;body?:string}[] : [];
  return <><section className="section architecture-soft"><div className="container"><SectionHead kicker={page?.eyebrow || "OEM / ODM Services"} title={page?.heading || "Lighting products shaped around your brand"} description={page?.body || "Bring an existing product brief or a new idea. We help define the development scope, samples and route to production."}/><div className="hero-actions"><Link href="/contact?type=OEM%20%2F%20ODM%20Request" className="btn-primary">Discuss Your Project</Link><Link href="/products" className="btn-secondary">Explore Existing Products</Link></div></div></section><section className="section"><div className="container"><div className="buyer-paths">{options.map(([title, body], i) => <article className="card" key={title}><div className="kicker">0{i+1}</div><h2>{saved[i]?.title || title}</h2><p>{saved[i]?.body || body}</p></article>)}</div></div></section><section className="section architecture-dark"><div className="container"><SectionHead title="A clear path to" accent="production"/><ol className="process-grid">{["Project brief", "Proposal & feasibility", "Sample approval", "Production & shipment"].map((title,i) => <li key={title}><span>0{i+1}</span><h3>{title}</h3></li>)}</ol></div></section><section className="section"><div className="container inquiry-brief"><h2>What to include in your brief</h2><p>Product references or sketches, intended use, target market, required functions, expected quantity, packaging needs and target launch date.</p><p>Sample costs, MOQ, testing scope and lead time are confirmed for each project.</p></div></section><ProjectCTA/></>;
}
